name: Java CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - name: Setup executable permissions on gradlew
        run: chmod +x ./app/gradlew
      - run: ./gradlew checkstyleMain
        working-directory: ./app
      - run: ./gradlew test
        working-directory: ./app
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.5.0
        env:
          CC_TEST_REPORTER_ID: fab317e682981024e0fcd36034a84a8707aa061036f3bd9a700fc30cbd657b88
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: make -C app report
          debug: true
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
